export enum Techs {
  React = "React",
  Vue = "Vue",
  Angular = "Angular",
  Flutter = "Flutter",
  Dart = "Dart",
  TypeScript = "TypeScript",
  JavaScript = "JavaScript",
  Node = "Node.js",
  ReactNative = "React Native",
  Next = "Next.js",
  Nest = "Nest.js",
  Docker = "Docker",
  Bun = "Bun",
  Git = "Git",
  GitHub = "GitHub",
  PostgreSQL = "PostgreSQL",
  SQLite = "SQLite",
}
